const Ie = 'EvenMoreVery123RandomText!@#$%^&*()_+';
const input = {
    cookie: "3.100000000000002",
    buildings: [
      {
        name: "Pickaxe",
        namePlural: "Pickaxes",
        id: "pickaxe",
        baseCost: "15",
        amountPurchased: 1,
        icon: "/cookie_crafter/pickaxe.png",
        description: "Autoclicks once every 10 seconds ^^",
        baseProduction: 0.1,
        productionMultiplier: 1,
        productionStats: 2.3000000000000007,
        productionPhrasePresent: "mines",
        productionPhrase: "mine",
        productionPhrasePast: "mined",
      }, {
        name: "Witch",
        namePlural: "Witches",
        id: "witch",
        baseCost: "100",
        amountPurchased: 0,
        icon: "/cookie_crafter/witch.png",
        description: "Grandma, is that you?",
        baseProduction: 1,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "conjure",
        productionPhrasePresent: "conjures",
        productionPhrasePast: "conjured",
      }, {
        name: "Farmland",
        namePlural: "Farmlands",
        id: "farmland",
        baseCost: "1100",
        amountPurchased: 0,
        icon: "/cookie_crafter/farmland.png",
        description: "Planting cookies!",
        baseProduction: 8,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "farm",
        productionPhrasePresent: "farms",
        productionPhrasePast: "farmed",
      }, {
        name: "Minecart",
        namePlural: "Minecarts",
        id: "minecart",
        baseCost: "12000",
        amountPurchased: 0,
        icon: "/cookie_crafter/minecart.png",
        description: "Into the mines!",
        baseProduction: 47,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "surface",
        productionPhrasePresent: "surfaces",
        productionPhrasePast: "surfaced",
      }, {
        name: "Crafter",
        namePlural: "Crafters",
        id: "crafter",
        baseCost: "130000",
        amountPurchased: 0,
        icon: "/cookie_crafter/crafter.png",
        description: "Gotta craft them all!",
        baseProduction: 260,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "craft",
        productionPhrasePresent: "crafts",
        productionPhrasePast: "crafted",
      }, {
        name: "Shulker Box",
        namePlural: "Shulker Boxes",
        id: "shulker_box",
        baseCost: "1400000",
        amountPurchased: 0,
        icon: "/gamedata/blockImages/shulker_box.png",
        description: "What's this? A shulker box monster?",
        baseProduction: 1400,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "store",
        productionPhrasePresent: "stores",
        productionPhrasePast: "stored",
      }, {
        name: "Totem of Cookie",
        namePlural: "Totems of Cookie",
        id: "totem_of_cookie",
        baseCost: "20000000",
        amountPurchased: 0,
        icon: "/gamedata/itemImages/totem_of_undying.png",
        description: "Saves all the cookies!",
        baseProduction: 7800,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "save",
        productionPhrasePresent: "saves",
        productionPhrasePast: "saved",
      }, {
        name: "End Ship",
        namePlural: "End Ships",
        id: "end_ship",
        baseCost: "330000000",
        amountPurchased: 0,
        icon: "/cookie_crafter/end_ship.webp",
        description: "Travels the void to deliver cookies!",
        baseProduction: 44000,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "deliver",
        productionPhrasePresent: "delivers",
        productionPhrasePast: "delivered",
      }, {
        name: "Elytra",
        namePlural: "Elytras",
        id: "elytra",
        baseCost: "5100000000",
        amountPurchased: 0,
        icon: "/gamedata/itemImages/elytra.png",
        description: "Ships cookies faster than the end ship using rocket boosts!",
        baseProduction: 260000,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "ship",
        productionPhrasePresent: "ships",
        productionPhrasePast: "shipped",
      }, {
        name: "Brewing Stand",
        namePlural: "Brewing Stands",
        id: "brewing_stand",
        baseCost: "75000000000",
        amountPurchased: 0,
        icon: "/gamedata/blockImages/brewing_stand.png",
        description: "Ships cookies faster than the end ship using rocket boosts!",
        baseProduction: 1600000,
        productionMultiplier: 1,
        productionStats: 0,
        productionPhrase: "ship",
        productionPhrasePresent: "ships",
        productionPhrasePast: "shipped",
      }
    ],
    upgrades: [
      {
        name: "Spoon",
        id: "spoon",
        icon: "/cookie_crafter/wooden_shovel.png",
        description: "Sturdy wooden spoon. Clicking is 2x more effective!",
        unlockTotalCookieRequirement: 1,
        unlocked: false,
        clickMultiplier: 2,
      }, {
        name: "Spoon MK2",
        id: "spoon_mk2",
        icon: "/cookie_crafter/stone_shovel.png",
        description: "Getting an upgrade! Another 2x clicking effectiveness!",
        unlockTotalCookieRequirement: 100,
        unlocked: false,
        clickMultiplier: 2,
      }, {
        name: "Spoon MK3",
        id: "spoon_mk3",
        icon: "/cookie_crafter/iron_shovel.png",
        description: "Isn't it iron spoon? Click it twice!",
        unlockTotalCookieRequirement: 1000,
        unlocked: false,
        clickMultiplier: 2,
      }, {
        name: "Spoon MK4",
        id: "spoon_mk4",
        icon: "/cookie_crafter/diamond_shovel.png",
        description: "Cover my spoon in diamonds! Twice the clicking!",
        unlockTotalCookieRequirement: 10000,
        unlocked: false,
        clickMultiplier: 2,
      }, {
        name: "Spoon MK5",
        id: "spoon_mk5",
        icon: "/cookie_crafter/netherite_shovel.png",
        description: "Hidden in the Dough! Covered with 2x efficiency!",
        unlockTotalCookieRequirement: 100000,
        unlocked: false,
        clickMultiplier: 2,
      }, {
        name: "Bucket",
        id: "bucket",
        icon: "/cookie_crafter/bucket.png",
        description: "Way more effective than a spoon! (x2)",
        unlockTotalCookieRequirement: 1000000,
        unlocked: false,
        clickMultiplier: 2,
      }, {
        name: "Milk Bucket",
        id: "milk_bucket",
        icon: "/cookie_crafter/milk_bucket.png",
        description: "Already pre-filled! And twice as fast!",
        unlockTotalCookieRequirement: 10000000,
        unlocked: false,
        clickMultiplier: 2,
      }, {
        name: "Lava Bucket",
        id: "lava_bucket",
        icon: "/cookie_crafter/lava_bucket.png",
        description: "Already helps with baking! Bakes 2x faster!",
        unlockTotalCookieRequirement: 100000000,
        unlocked: false,
        clickMultiplier: 2,
      }, {
        name: "Cookie Boat",
        id: "cookie_boat",
        icon: "/cookie_crafter/oak_boat.png",
        description: "Sails the seas of cookies! Cuts the time in half!",
        unlockTotalCookieRequirement: 1000000000,
        unlocked: false,
        clickMultiplier: 2,
      }
    ],
    bakeryName: "Cookie Doe's Bakery",
    maxCookies: "16",
    totalCookies: "18.10000000000003",
  };

function xt(e: any) {
	let o = JSON.stringify(e) + Ie;
	return btoa(o).split('').reverse().join('');
}

const result = xt(input);

console.log(JSON.stringify(result));
